### PR TITLE
Rename lahn_1 to lahn_marb, lahn_2 to lahn_leun, lahn_3 to lahn_kalk …

### PR DESCRIPTION
**Pull request by parvumflumen**
…and lahn_dill to lahn_assl

Exchange series files for lahn model
Update doctests

### CODE REVIEW

**Comment by tyralla** [comment]
Thanks for providing this PR!

The tests did not run due to a merge conflict.  I resolved the conflict and will look at the test results later.

**Comment by parvumflumen** [comment]
> The tests did not run due to a merge conflict. I resolved the conflict and will look at the test results later.

There are still some issues to solve, especially the reason for the wrong input.t series after simulation and writing of nc files is still not found

**Comment by tyralla** [comment]
> There are still some issues to solve, especially the reason for the wrong input.t series after simulation and writing of nc files is still not found

I am quite confident this is due to a bug to be fixed by 8ab0ef1d1539a14e50d84f3451a57887ee9d987b.  Luckily, we detected it before releasing HydPy 6.0.   It occurred only on the rare occasion of reading or writing data "just in time" and the first dates of the initialisation period being different from the first date of the data period of the NetCDF file.   Thanks to the new data for the HydPy-H-Lahn example project, this case is now covered by our test suite.

**Comment by tyralla** [comment]
> I am quite confident this is due to a bug to be fixed by [8ab0ef1](https://github.com/hydpy-dev/hydpy/commit/8ab0ef1d1539a14e50d84f3451a57887ee9d987b). Luckily, we detected it before releasing HydPy 6.0. It occurred only on the rare occasion of reading or writing data "just in time" and the first dates of the initialisation period being different from the first date of the data period of the NetCDF file. Thanks to the new data for the HydPy-H-Lahn example project, this case is now covered by our test suite.

I merged and pushed, so you should already have the test results when coming back at it.  (For some reason, the jobs started twice on AppVeyor and Travis - I cancelled the redundant ones.)

**Review by tyralla — CHANGES_REQUESTED** [review]
Neary finished, it seems.  Looking for further text sections where we might need to adapt to the new numbers of names seems like too much work to be worth it, considering you already invested much time.  But three (larger) things need adjustment:

- Now, a huge amount of lines is too long (see the Python 3.9 job on Travis-CI).
- The `summarise_ncfile` in `project_structure.rst` fails. (use ellipsis markers in the file path, "...data/HydPy-H-Lahn/series/default/hland_96_input_p.nc" or so)
- Please revert the change to function `prepare_full_example_2`.  As you correctly said offline, passing other dates to the "first_date" argument would require corresponding initial conditions not offered by the'HydPy-H-Lahn' example project.

**Review by tyralla — APPROVED** [review]
Looks good now. Thanks!

**Pull request merged**
